# Cloud Build trigger configuration for production environment
name: imgstream-production-deploy
description: "Deploy ImgStream to production environment"

# Trigger configuration
github:
  owner: YOUR_GITHUB_USERNAME
  name: YOUR_REPO_NAME
  push:
    tag: ^v.*

# Build configuration
filename: cloudbuild.yaml

# Substitutions for production environment
substitutions:
  _ENVIRONMENT: production
  _REGION: us-central1
  _MEMORY_LIMIT: 2Gi
  _CPU_LIMIT: 2000m
  _CONCURRENCY: "100"
  _MAX_INSTANCES: "50"
  _MIN_INSTANCES: "2"
  _VERSION: ${TAG_NAME}

# Service account for the build
serviceAccount: projects/$PROJECT_ID/serviceAccounts/cloudbuild-production@$PROJECT_ID.iam.gserviceaccount.com

# Build timeout
timeout: 1800s

# Additional options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitutionOption: ALLOW_LOOSE

# Approval required for production
approvalConfig:
  approvalRequired: true
