# Cloud Monitoring Alert Policies Configuration for ImgStream
# This file defines alert policies for monitoring the application

alertPolicies:
  # Cloud Run Service Health Alerts
  - name: "imgstream-service-availability"
    displayName: "ImgStream Service Availability"
    documentation:
      content: |
        This alert fires when the ImgStream Cloud Run service availability drops below 99%.
        This could indicate service outages or deployment issues.
        
        Troubleshooting steps:
        1. Check Cloud Run service logs
        2. Verify recent deployments
        3. Check resource limits and scaling settings
        4. Review error rates and response times
    conditions:
      - displayName: "Service availability below 99%"
        conditionThreshold:
          filter: |
            resource.type="cloud_run_revision"
            resource.labels.service_name=~"imgstream-.*"
            metric.type="run.googleapis.com/request_count"
          comparison: COMPARISON_LESS_THAN
          thresholdValue: 0.99
          duration: "300s"
          aggregations:
            - alignmentPeriod: "60s"
              perSeriesAligner: ALIGN_RATE
              crossSeriesReducer: REDUCE_MEAN
              groupByFields:
                - "resource.labels.service_name"
    combiner: OR
    enabled: true
    notificationChannels: []
    alertStrategy:
      autoClose: "1800s"

  # High Error Rate Alert
  - name: "imgstream-high-error-rate"
    displayName: "ImgStream High Error Rate"
    documentation:
      content: |
        This alert fires when the error rate exceeds 5% over a 5-minute period.
        
        Troubleshooting steps:
        1. Check application logs for error patterns
        2. Verify database connectivity
        3. Check GCS bucket accessibility
        4. Review authentication configuration
        5. Check resource limits and memory usage
    conditions:
      - displayName: "Error rate above 5%"
        conditionThreshold:
          filter: |
            resource.type="cloud_run_revision"
            resource.labels.service_name=~"imgstream-.*"
            metric.type="run.googleapis.com/request_count"
            metric.labels.response_code_class!="2xx"
          comparison: COMPARISON_GREATER_THAN
          thresholdValue: 0.05
          duration: "300s"
          aggregations:
            - alignmentPeriod: "60s"
              perSeriesAligner: ALIGN_RATE
              crossSeriesReducer: REDUCE_SUM
              groupByFields:
                - "resource.labels.service_name"
    combiner: OR
    enabled: true
    notificationChannels: []

  # High Response Time Alert
  - name: "imgstream-high-response-time"
    displayName: "ImgStream High Response Time"
    documentation:
      content: |
        This alert fires when the 95th percentile response time exceeds 2 seconds.
        
        Troubleshooting steps:
        1. Check CPU and memory utilization
        2. Review database query performance
        3. Check GCS operation latency
        4. Verify image processing performance
        5. Consider scaling up resources
    conditions:
      - displayName: "95th percentile response time above 2s"
        conditionThreshold:
          filter: |
            resource.type="cloud_run_revision"
            resource.labels.service_name=~"imgstream-.*"
            metric.type="run.googleapis.com/request_latencies"
          comparison: COMPARISON_GREATER_THAN
          thresholdValue: 2000
          duration: "300s"
          aggregations:
            - alignmentPeriod: "60s"
              perSeriesAligner: ALIGN_DELTA
              crossSeriesReducer: REDUCE_PERCENTILE_95
              groupByFields:
                - "resource.labels.service_name"
    combiner: OR
    enabled: true
    notificationChannels: []

  # Memory Usage Alert
  - name: "imgstream-high-memory-usage"
    displayName: "ImgStream High Memory Usage"
    documentation:
      content: |
        This alert fires when memory utilization exceeds 80%.
        
        Troubleshooting steps:
        1. Check for memory leaks in application logs
        2. Review image processing operations
        3. Consider increasing memory limits
        4. Check for inefficient database queries
        5. Monitor garbage collection patterns
    conditions:
      - displayName: "Memory utilization above 80%"
        conditionThreshold:
          filter: |
            resource.type="cloud_run_revision"
            resource.labels.service_name=~"imgstream-.*"
            metric.type="run.googleapis.com/container/memory/utilizations"
          comparison: COMPARISON_GREATER_THAN
          thresholdValue: 0.8
          duration: "300s"
          aggregations:
            - alignmentPeriod: "60s"
              perSeriesAligner: ALIGN_MEAN
              crossSeriesReducer: REDUCE_MEAN
              groupByFields:
                - "resource.labels.service_name"
    combiner: OR
    enabled: true
    notificationChannels: []

  # CPU Usage Alert
  - name: "imgstream-high-cpu-usage"
    displayName: "ImgStream High CPU Usage"
    documentation:
      content: |
        This alert fires when CPU utilization exceeds 80%.
        
        Troubleshooting steps:
        1. Check for CPU-intensive operations
        2. Review image processing workload
        3. Consider increasing CPU allocation
        4. Check for inefficient algorithms
        5. Monitor concurrent request handling
    conditions:
      - displayName: "CPU utilization above 80%"
        conditionThreshold:
          filter: |
            resource.type="cloud_run_revision"
            resource.labels.service_name=~"imgstream-.*"
            metric.type="run.googleapis.com/container/cpu/utilizations"
          comparison: COMPARISON_GREATER_THAN
          thresholdValue: 0.8
          duration: "300s"
          aggregations:
            - alignmentPeriod: "60s"
              perSeriesAligner: ALIGN_MEAN
              crossSeriesReducer: REDUCE_MEAN
              groupByFields:
                - "resource.labels.service_name"
    combiner: OR
    enabled: true
    notificationChannels: []

  # GCS Storage Usage Alert
  - name: "imgstream-high-storage-usage"
    displayName: "ImgStream High Storage Usage"
    documentation:
      content: |
        This alert fires when GCS bucket usage exceeds 80% of the expected limit.
        
        Troubleshooting steps:
        1. Review storage usage patterns
        2. Check for large or unnecessary files
        3. Implement storage cleanup policies
        4. Consider storage lifecycle management
        5. Monitor upload patterns for anomalies
    conditions:
      - displayName: "GCS bucket usage above threshold"
        conditionThreshold:
          filter: |
            resource.type="gcs_bucket"
            resource.labels.bucket_name=~".*imgstream.*"
            metric.type="storage.googleapis.com/storage/total_bytes"
          comparison: COMPARISON_GREATER_THAN
          thresholdValue: 85899345920  # 80GB in bytes
          duration: "300s"
          aggregations:
            - alignmentPeriod: "3600s"
              perSeriesAligner: ALIGN_MEAN
              crossSeriesReducer: REDUCE_SUM
              groupByFields:
                - "resource.labels.bucket_name"
    combiner: OR
    enabled: true
    notificationChannels: []

  # Instance Count Alert
  - name: "imgstream-instance-scaling"
    displayName: "ImgStream Instance Scaling"
    documentation:
      content: |
        This alert fires when the number of instances approaches the maximum limit.
        
        Troubleshooting steps:
        1. Review traffic patterns
        2. Check for traffic spikes or DDoS
        3. Consider increasing max instances
        4. Review auto-scaling configuration
        5. Monitor request queue length
    conditions:
      - displayName: "Instance count near maximum"
        conditionThreshold:
          filter: |
            resource.type="cloud_run_revision"
            resource.labels.service_name=~"imgstream-.*"
            metric.type="run.googleapis.com/container/instance_count"
          comparison: COMPARISON_GREATER_THAN
          thresholdValue: 40  # 80% of max 50 instances
          duration: "300s"
          aggregations:
            - alignmentPeriod: "60s"
              perSeriesAligner: ALIGN_MEAN
              crossSeriesReducer: REDUCE_MAX
              groupByFields:
                - "resource.labels.service_name"
    combiner: OR
    enabled: true
    notificationChannels: []

# Notification Channels Configuration
notificationChannels:
  - type: "email"
    displayName: "ImgStream Operations Team"
    description: "Email notifications for ImgStream alerts"
    labels:
      email_address: "ops@example.com"
    enabled: true

  - type: "slack"
    displayName: "ImgStream Slack Channel"
    description: "Slack notifications for ImgStream alerts"
    labels:
      channel_name: "#imgstream-alerts"
      url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    enabled: false  # Enable when Slack webhook is configured

# Dashboard Configuration
dashboards:
  - name: "imgstream-overview"
    displayName: "ImgStream Overview Dashboard"
    widgets:
      - title: "Request Rate"
        type: "line_chart"
        metrics:
          - "run.googleapis.com/request_count"
        filters:
          - 'resource.labels.service_name=~"imgstream-.*"'
        
      - title: "Error Rate"
        type: "line_chart"
        metrics:
          - "run.googleapis.com/request_count"
        filters:
          - 'resource.labels.service_name=~"imgstream-.*"'
          - 'metric.labels.response_code_class!="2xx"'
          
      - title: "Response Time (95th percentile)"
        type: "line_chart"
        metrics:
          - "run.googleapis.com/request_latencies"
        aggregation: "REDUCE_PERCENTILE_95"
        filters:
          - 'resource.labels.service_name=~"imgstream-.*"'
          
      - title: "Memory Utilization"
        type: "line_chart"
        metrics:
          - "run.googleapis.com/container/memory/utilizations"
        filters:
          - 'resource.labels.service_name=~"imgstream-.*"'
          
      - title: "CPU Utilization"
        type: "line_chart"
        metrics:
          - "run.googleapis.com/container/cpu/utilizations"
        filters:
          - 'resource.labels.service_name=~"imgstream-.*"'
          
      - title: "Instance Count"
        type: "line_chart"
        metrics:
          - "run.googleapis.com/container/instance_count"
        filters:
          - 'resource.labels.service_name=~"imgstream-.*"'
          
      - title: "Storage Usage"
        type: "gauge"
        metrics:
          - "storage.googleapis.com/storage/total_bytes"
        filters:
          - 'resource.labels.bucket_name=~".*imgstream.*"'
